export { default as advancedFiltersIcon } from './advanced-filters.svg';
export { default as batchScanningIcon } from './batch-scanning.svg';
export { default as documentScannerIcon } from './document-scanner.svg';
export { default as exportShareIcon } from './export-share.svg';
export { default as signStampIcon } from './sign-stamp.svg';
export { default as pdfIcon } from './pdf_icon.png';
export { default as exportPdfIcon } from './export_pdf.png';
export { default as exportTxtIcon } from './export_txt.png';
export { default as exportJpgIcon } from './export_jpg.png';
